name: 'OpenShift Action'
description: "This action installs 'oc', the OpenShift Client."
author: 'Red Hat'
branding:
  icon: circle
  color: red
inputs:
  oc_version:
    description: "oc version to install. It can be a version (eg. 4.6.0) or a URL pointing to an oc download. If left blank, the latest oc is installed."
    default: 'latest'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
