name: Verify Bundle
on: [ push, pull_request ]
env:
  BUNDLE_FILE: "dist/index.js"
  BUNDLE_COMMAND: "npm run bundle"
jobs:
  verify-latest:
    name: Verify Latest Bundle
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install
      run: npm ci

    - name: Verify Latest Bundle
      uses: tetchel/bundle-verifier-action@master
      with:
        bundle_file: ${{ env.BUNDLE_FILE }}
        bundle_command: ${{ env.BUNDLE_COMMAND }}
